# Generated by Django 5.2.6 on 2025-09-16 20:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mamono', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.IntegerField(default=0)),
                ('experience', models.IntegerField(default=0)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guilds', to='mamono.discordguild')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='mamono.discorduser')),
            ],
            options={
                'unique_together': {('guild', 'user')},
            },
        ),
        migrations.CreateModel(
            name='DiscordSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope_type', models.CharField(choices=[('GUILD', 'Guild'), ('USER', 'User'), ('BOT', 'Bot')], max_length=5)),
                ('scope_id', models.CharField(blank=True, max_length=100, null=True)),
                ('setting_key', models.CharField(max_length=100)),
                ('setting_value', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='discordlevels',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='discordlevels',
            name='guild',
        ),
        migrations.RemoveField(
            model_name='discordlevels',
            name='user',
        ),
        migrations.DeleteModel(
            name='DiscordSettings',
        ),
        migrations.DeleteModel(
            name='DiscordLevels',
        ),
    ]
